### ISSUE TITLE
Alternative RS485 repeater?

### ISSUE THREAD

**Issue by 0rangutan** [Jumpy07/Solis---SolisCloud-and-Home-Assistant#4]
Would this work as a cheaper alternative RS485 repeater?
https://www.amazon.co.uk/gp/product/B07X2GM3VY

**Comment by hippytyre** [comment]
I hope so, I'm building my set-up tomorrow using one.

**Comment by 0rangutan** [comment]
Good luck - please share how you get on.

**Comment by alienatedsec** [comment]
It says that it 
```
....can be used to extend the RS485 distance to up to 4000 ft (1.2km), or to convert 1 channel 2-wire RS485 to 2 channel 2-wire RS485.
```

If you follow the RS485 standard and Modbus, it will allow you to connect two inverters (Slave devices), but not an inverter (Slave) and datalogger (Master).

**Comment by hippytyre** [comment]
> Good luck - please share how you get on.

It's not quite as neat as I would have liked but I'll go back and neaten it up. It works perfectly though.

![PXL_20231204_151357944 MP](https://github.com/Jumpy07/Solis---SolisCloud-and-Home-Assistant/assets/33829658/cc6c0631-6074-4e74-8a16-2ff82479fc3a)

**Comment by Ghysbrecht** [comment]
@hippytyre Is it still working fine? I would not expect that board to actually fully function as it does nothing special. The one recommended by the repo owner has some intelligence where it is built to allow two masters, which request data, to use the same modbus, and thus the same slave device (inverter). I believe the board that you used just provides a safer way of linking multiple devices together with one master. I would expect this to work fine until both the wifi stick & the USB converter are requesting data at the same time. This will probably cause a collision. Maybe most of the time, this is working fine since the wifi stick may be polling data very sporadically.

**Comment by hippytyre** [comment]
All I can tell you is that I've had no issues since I wired it all up. It all works perfectly

**Comment by Jumpy07** [comment]
Software is outwith my Github project..which is purely hardware....hence have not responded.....Sent from Outlook for Android

**Comment by ececconi99** [comment]
> Software is outwith my Github project..

not sure what you mean by "outwith"
